[toolchain]
solana_version = "2.1.5"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cpi_swap_program = "B1ph2kyNtkhscRQ3R1CAwMNM4PbGGvphHTzxR83kRsRc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=bcb20675-41a2-43f9-a1c9-67dd56e47dd9"
wallet = "~/.config/solana/id.json"

[scripts]
deploy-local = "solana program deploy target/deploy/cpi_swap_program.so --program-id target/deploy/cpi_swap_program-keypair.json -C ~/.config/solana/cli/local.yml --use-rpc --with-compute-unit-price 10"
deploy-mainnet = "solana program deploy target/deploy/cpi_swap_program.so --program-id target/deploy/cpi_swap_program-keypair.json -C ~/.config/solana/cli/config.yml --use-rpc --with-compute-unit-price 10"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
